name: talent_link
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  socket_io_client: ^2.0.3+1
  http: ^0.13.6
  jwt_decoder: ^2.0.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  image_picker: ^1.1.2
  file_picker: ^10.1.1
  url_launcher: ^6.3.1
  device_preview: ^1.2.0
  intl: ^0.19.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
