name: talent_link
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.6
  jwt_decoder: ^2.0.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  socket_io_client: ^3.1.2
  image_picker: ^1.1.2
  file_picker: ^8.3.7
  url_launcher: ^6.3.1
  device_preview: ^1.2.0
  intl: ^0.19.0
  web_socket_channel: ^3.0.3
  zego_uikit_prebuilt_video_conference: ^2.9.9
  permission_handler: ^11.4.0
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  flutter_polyline_points: ^1.0.0

  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.4
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^18.0.1
  provider: ^6.0.5

  flutter_typeahead: ^4.3.7
  geocoding: ^2.1.0


 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
