// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaqjttBZj17Hii5TgDAvEA25UNMuOowYM',
    appId: '1:108057330755:web:387106f4824330ea6780f6',
    messagingSenderId: '108057330755',
    projectId: 'talentlink-187ca',
    authDomain: 'talentlink-187ca.firebaseapp.com',
    storageBucket: 'talentlink-187ca.firebasestorage.app',
    measurementId: 'G-RGMF1HQCJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy8dOXM5Eu8TmuU8kUjL9ERtebGdpzvIQ',
    appId: '1:108057330755:android:92fad410aa954c5e6780f6',
    messagingSenderId: '108057330755',
    projectId: 'talentlink-187ca',
    storageBucket: 'talentlink-187ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvSPHWzk3nsWLebD60vvRt0cQi6VHass',
    appId: '1:108057330755:ios:5a78b0e2ebd13b386780f6',
    messagingSenderId: '108057330755',
    projectId: 'talentlink-187ca',
    storageBucket: 'talentlink-187ca.firebasestorage.app',
    iosBundleId: 'com.example.talentLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtvSPHWzk3nsWLebD60vvRt0cQi6VHass',
    appId: '1:108057330755:ios:5a78b0e2ebd13b386780f6',
    messagingSenderId: '108057330755',
    projectId: 'talentlink-187ca',
    storageBucket: 'talentlink-187ca.firebasestorage.app',
    iosBundleId: 'com.example.talentLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaqjttBZj17Hii5TgDAvEA25UNMuOowYM',
    appId: '1:108057330755:web:0cf391db3696705c6780f6',
    messagingSenderId: '108057330755',
    projectId: 'talentlink-187ca',
    authDomain: 'talentlink-187ca.firebaseapp.com',
    storageBucket: 'talentlink-187ca.firebasestorage.app',
    measurementId: 'G-ZPEY36H2QB',
  );
}
